pipeline {
    agent any
  
    tools {
      go 'go-1.16.8'
    }
  
    stages {
        stage('Git checkout') {
            steps{
                // Get source code from a GitHub repository
                git branch:'main', url:'https://github.com/nini1108/openhack-devops-team/'
            }
        }
        
        stage('Build') {
            steps{
                // Do your build task
                sh 'go run main.go'
            }
        }
        
        stage('Test') {
            steps{
                // Run unit tests, integration tests, and/or e2e tests
            }
        }
        
        stage('Publish') {
            steps{
                // Publish your artifacts to somewhere.
                // However, in our hands-on, you just need to print the artifact list by Linux command 'ls -la'
            }
        }

        post {
            always { 
                echo 'I will always say Hello again!'
            }
        }
    }
}
